### ISSUE TITLE
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

### ISSUE THREAD

**Issue by meltingCat** [aa-samad/conv_snn#10]
Got an error in **Training & Testing** 

```
(conv_snn) test@test-dual1060:~/Desktop/project/conv_snn/CIFAR10-DVS$ python3 main.py
device cuda
  0%|                                                                                                      | 0/1750 [00:00<?, ?it/s]
==> Build model and setup loss and optimizer
==> Epoch:[0/500][training stage]
  0%|                                                                                                      | 0/1750 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 231, in <module>
    main()
  File "main.py", line 65, in main
    model.run()
  File "main.py", line 124, in run
    self.train_1epoch()
  File "main.py", line 172, in train_1epoch
    prec1, prec5 = accuracy(output.data, label.cuda(), topk=(1, 5))
  File "/home/test/Desktop/project/conv_snn/CIFAR10-DVS/utils.py", line 30, in accuracy
    correct_k = correct[:k].view(-1).float().sum(0)
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
```

**Comment by aa-samad** [comment]
what is the dataset?! what are the shapes?! is this the default dataset?!
please also provide the pytorch version.

**Comment by meltingCat** [comment]
thanks for reply so fast.
Training dvs-cifar10 and all settings were default, just following the readme.

pytorch version is 1.7.1

**Comment by meltingCat** [comment]
I add contiguous() to line30 in `conv_snn/CIFAR10-DVS/utils.py/` and start to train
`correct_k = correct[:k].contiguous().view(-1).float().sum(0)`

but got another error  `FileNotFoundError: [Errno 2] No such file or directory: 'record/spatial/rgb_train.csv'`

**Comment by aa-samad** [comment]
it is my job ;)
well it appears there is a difference in view function of newer pytorch versions, 
the second problem is odd!!
ok, i don't have access to my laptop now, it will take approx 12 hours to check this.
I will inform you about the problem and the possible fix.

**Comment by meltingCat** [comment]
```
device cuda
  0%|                                                                                                      | 0/1750 [00:00<?, ?it/s]
==> Build model and setup loss and optimizer
==> Epoch:[0/500][training stage]
100%|███████████████████████████████████████████████████████████████████████████████████████████| 1750/1750 [02:05<00:00, 13.90it/s]
Time [0.072] Data [0.002] 
Loss [2.286] Prec@1 [13.4429] Prec@5 [54.4143]
LR 0.0005

Traceback (most recent call last):
  File "main.py", line 233, in <module>
    main()
  File "main.py", line 65, in main
    model.run()
  File "main.py", line 124, in run
    self.train_1epoch()
  File "main.py", line 199, in train_1epoch
    record_info(info, 'record/spatial/rgb_train.csv','train')
  File "/home/test/Desktop/project/conv_snn/CIFAR10-DVS/utils.py", line 85, in record_info
    df.to_csv(filename,index=False,columns=column_names)
  File "/home/test/anaconda3/envs/conv_snn/lib/python3.6/site-packages/pandas/core/generic.py", line 3170, in to_csv
    formatter.save()
  File "/home/test/anaconda3/envs/conv_snn/lib/python3.6/site-packages/pandas/io/formats/csvs.py", line 190, in save
    compression=dict(self.compression_args, method=self.compression),
  File "/home/test/anaconda3/envs/conv_snn/lib/python3.6/site-packages/pandas/io/common.py", line 493, in get_handle
    f = open(path_or_buf, mode, encoding=encoding, errors=errors, newline="")
FileNotFoundError: [Errno 2] No such file or directory: 'record/spatial/rgb_train.csv'
```
